"use client";
import {useState} from "react";
const questions=[
{area:"Matemática",tag:"Problemas do cotidiano",title:"Consumo de água",text:"Uma família acompanha seu consumo mensal de água. Em janeiro, consumiu 18 m³. Em fevereiro, o consumo caiu para 15 m³. Qual foi aproximadamente a redução percentual no consumo?",options:["10%","17%","20%","25%"],answer:1,explanation:"A redução foi de 3 m³. Dividindo 3 por 18, temos aproximadamente 16,7%, que pode ser arredondado para 17%."},
{area:"Ciências",tag:"Interpretação de dados",title:"Temperatura e energia",text:"Uma escola instalou painéis solares e passou a registrar a quantidade de energia produzida diariamente. Em dias nublados, a produção foi menor. Qual explicação é mais adequada?",options:["As nuvens aumentam a massa dos painéis.","A luz disponível para os painéis é menor.","A temperatura sempre impede a produção.","Os painéis produzem energia apenas à noite."],answer:1,explanation:"Painéis solares dependem da radiação luminosa. Com menor disponibilidade de luz, a geração tende a diminuir."},
{area:"Leitura",tag:"Análise de informação",title:"Uma decisão coletiva",text:"Uma comunidade precisa escolher entre duas propostas para melhorar uma praça. Antes da decisão, os moradores recebem um relatório com custos, benefícios e impactos de cada alternativa. O que essa informação permite fazer?",options:["Eliminar qualquer opinião pessoal.","Tomar uma decisão baseada em informações comparáveis.","Garantir que todos escolherão a mesma proposta.","Evitar a necessidade de analisar os dados."],answer:1,explanation:"Comparar custos, benefícios e impactos ajuda as pessoas a avaliar as alternativas com base em informações."}
];
export default function Home(){
 const [started,setStarted]=useState(false),[q,setQ]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(false);
 const current=questions[q];
 function next(){if(selected===current.answer)setScore(score+1);if(q===questions.length-1)setDone(true);else{setQ(q+1);setSelected(null)}}
 if(!started)return <main className="home"><div className="hero"><span className="eyebrow">AVALIAÇÃO POR COMPETÊNCIAS</span><h1>PISA <b>Brasil</b></h1><p>Teste seus conhecimentos com questões contextualizadas, inspiradas em situações do cotidiano.</p><div className="cards"><div><strong>3</strong><span>questões</span></div><div><strong>3</strong><span>áreas</span></div><div><strong>~5 min</strong><span>de duração</span></div></div><button onClick={()=>setStarted(true)}>Começar avaliação <span>→</span></button><small>Esta é uma demonstração com questões autorais.</small></div></main>;
 if(done)return <main className="home"><div className="result"><span className="eyebrow">AVALIAÇÃO CONCLUÍDA</span><div className="score">{score}<small>/ {questions.length}</small></div><h1>Seu resultado</h1><p>Você acertou {score} de {questions.length} questões.</p><button onClick={()=>{setStarted(false);setQ(0);setScore(0);setDone(false);setSelected(null)}}>Fazer novamente</button></div></main>;
 return <main className="test"><header><div className="brand">PISA <b>Brasil</b></div><div className="counter">Questão {q+1} de {questions.length}</div></header><div className="progress"><i style={{width:`${((q+1)/questions.length)*100}%`}}/></div><section className="question"><div className="meta"><span>{current.area}</span><em>{current.tag}</em></div><h1>{current.title}</h1><p className="statement">{current.text}</p><div className="options">{current.options.map((o,i)=><button className={selected===i?"selected":""} onClick={()=>setSelected(i)} key={o}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div><div className="bottom"><small>{selected===null?"Selecione uma alternativa para continuar.":"Alternativa selecionada."}</small><button disabled={selected===null} onClick={next}>{q===questions.length-1?"Finalizar":"Próxima questão"} <span>→</span></button></div></section></main>
}